version: 2
updates:
  - package-ecosystem: "gomod"
    versioning-strategy: lockfile-only
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
      - "gomod"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    allow:
      - dependency-type: "direct"
    # Critical fix for ARG-based Docker builds
    rebase-strategy: "disabled"  # Prevents PR conflicts with Docker updates

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["v4", "v5"]
      - dependency-name: "*"
        update-types: ["version-update:semver-prerelease"]

  - package-ecosystem: "docker"
    directory: "/"  # Must match Dockerfile location
    schedule:
      interval: "daily"
      time: "08:00"
    open-pull-requests-limit: 3
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
      - "docker"
      - "stretch"  # Critical: Track legacy Debian base
    commit-message:
      prefix: "container"
      include: "scope"
    ignore:
      # Block incompatible Debian bases (critical for your stretch dependency)
      - dependency-name: "golang"
        versions: [
          "*-buster", 
          "*-bullseye", 
          "*-bookworm",
          "*-trixie",
          "latest"
        ]
      # Prevent digest churn for stable tags
      - dependency-name: "golang"
        update-types: ["version-update:digest"]
      # Block unsupported stretch updates (EOL since 2020)
      - dependency-name: "library/debian"
        versions: ["stretch", "9"]  # Already pinned in your Dockerfile
    allow:
      - dependency-name: "golang"  # Only allow golang updates
        versions: ["*-stretch"]    # Enforce stretch compatibility
    versioning-strategy: "lockfile-only"
    # Critical: Handle ARG-based base images
    registries:
      - "dockerhub"  # Required for ARG resolution
