version: 2
updates:
  - package-ecosystem: "gomod"
    versioning-strategy: lockfile-only
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
      - "gomod"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    # Security hardening: Prevent indirect dependency updates
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["v4", "v5"]
      # Critical addition: Block unstable pre-releases
      - dependency-name: "*"
        update-types: ["version-update:semver-prerelease"]

  - package-ecosystem: "docker"
    directory: "/"  # Critical: Must match Dockerfile location
    schedule:
      interval: "daily"
      time: "08:00"  # Staggered to avoid concurrent runs
    open-pull-requests-limit: 3  # Reduced (Docker updates are higher-risk)
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
      - "docker"
    commit-message:
      prefix: "container"
      include: "scope"
    # Critical Docker-specific rules:
    ignore:
      # Block unstable tags
      - dependency-name: "library/alpine"
        versions: ["edge", "latest"]
      - dependency-name: "library/debian"
        versions: ["unstable", "sid"]
      # Prevent digest-only updates (no version change)
      - dependency-name: "*"
        update-types: ["version-update:digest"]
    # Security hardening:
    allow:
      - dependency-type: "direct"
    # Critical: Enable version pinning enforcement
    versioning-strategy: "lockfile-only"
