version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      # Critical fix: Add time to avoid GitHub rate limits
      time: "04:00"
    open-pull-requests-limit: 5  # Reduced from 10 to prevent overload
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
      - "gomod"  # Ecosystem-specific label
    commit-message:
      prefix: "deps"
      include: "scope"
    # Critical addition: Ignore pseudo-versions
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      # Critical fix: Add time offset to avoid concurrent runs
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: "main"  # Critical fix: Missing in original
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"  # Ecosystem-specific label
    commit-message:
      prefix: "ci"
      include: "scope"
    # Critical addition: Ignore workflow-only updates
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["v4", "v5"]  # Example: Pin to v3

        - package-ecosystem: "docker"
    directory: "/"  # Critical: Must match Dockerfile location
    schedule:
      interval: "daily"
      time: "08:00"  # Staggered to avoid concurrent runs
    open-pull-requests-limit: 3  # Reduced (Docker updates are higher-risk)
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
      - "docker"
    commit-message:
      prefix: "container"
      include: "scope"
    # Critical Docker-specific rules:
    ignore:
      # Block unstable tags
      - dependency-name: "library/alpine"
        versions: ["edge", "latest"]
      - dependency-name: "library/debian"
        versions: ["unstable", "sid"]
      # Prevent digest-only updates (no version change)
      - dependency-name: "*"
        update-types: ["version-update:digest"]
    # Security hardening:
    allow:
      - dependency-type: "direct"
    # Critical: Enable version pinning enforcement
    versioning-strategy: "lockfile-only"
