#!/bin/sh

dir=$(dirname $0)
dir=$(readlink -f $dir)
prevdir=$(pwd)
cd $dir

ver=$1
image="sharenix:${ver}"
pkgpath=/usr/local/go/src/github.com/duncte123/sharenix

dockerbuild() {
  docker build \
    --build-arg PREFIX="$1" \
    --build-arg ARCH="$2" \
    -t $3 . \
    || return 1

  docker run --rm \
    -v $dir:$pkgpath \
    -w $pkgpath \
    $3 \
    || return 1
}

dockerbuild golang x86_64 $image || exit $?
# Don't need i386 for my own purposes :)
# dockerbuild i386/golang i386 ${image}i386 || exit $?

cd $prevdir
