name: Release ShareNix

on:
  workflow_dispatch: {}

jobs:
  sharenix_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          path: './'
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: ./package

      - name: List files
        run: ls -hal
